import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import DashboardLayout from "@/components/DashboardLayout";
import { AlertTriangle, BriefcaseBusiness, CheckCircle2, ChevronRight, CircleDollarSign, ClipboardList, ShieldCheck, Star, Users, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { useState } from "react";

export default function AdminDashboard() {
  const { user, loading } = useAuth();
  const overview = trpc.admin.overview.useQuery(undefined, { enabled: user?.role === "admin" });
  const professionals = trpc.admin.listProfessionals.useQuery(undefined, { enabled: user?.role === "admin" });
  const activatePro = trpc.admin.activatePro.useMutation({ onSuccess: () => { void professionals.refetch(); void overview.refetch(); toast.success("Plano Pro ativado!"); }, onError: error => toast.error(error.message) });
  const deactivatePro = trpc.admin.deactivatePro.useMutation({ onSuccess: () => { void professionals.refetch(); void overview.refetch(); toast.success("Plano revertido para Essencial."); }, onError: error => toast.error(error.message) });
  const [tab, setTab] = useState<"overview" | "profissionais">("overview");

  if (loading) return <Loading />;
  return <DashboardLayout><div className="min-h-[calc(100vh-32px)] bg-[#f6f7fb] p-2 md:p-6">{user?.role !== "admin" ? <div className="mx-auto max-w-xl rounded-3xl border border-slate-200 bg-white p-10 text-center shadow-card"><AlertTriangle className="mx-auto h-10 w-10 text-amber-500" /><h1 className="display-font mt-5 text-2xl font-bold text-slate-950">Área restrita</h1><p className="mt-2 text-sm leading-6 text-slate-500">Este painel é exclusivo para administradores do ChamaPro.</p></div> : <><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><span className="mb-3 inline-flex items-center gap-2 rounded-full bg-slate-900 px-3 py-1 text-xs font-bold uppercase tracking-[.16em] text-white"><ShieldCheck className="h-3.5 w-3.5" /> Operação</span><h1 className="display-font text-3xl font-bold tracking-[-.05em] text-slate-950">Visão geral do ChamaPro</h1><p className="mt-2 text-sm text-slate-500">Acompanhe liquidez do marketplace, aquisição e monetização.</p></div><Button variant="outline" className="w-fit rounded-xl" onClick={() => { void overview.refetch(); void professionals.refetch(); }}>Atualizar dados</Button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Clientes" value={overview.data?.customers ?? 0} helper="perfis cadastrados" icon={<Users />} color="blue" /><Stat label="Profissionais" value={overview.data?.professionals ?? 0} helper="perfis ativos" icon={<BriefcaseBusiness />} color="violet" /><Stat label="Pedidos abertos" value={overview.data?.openRequests ?? 0} helper="aguardando resposta" icon={<ClipboardList />} color="amber" /><Stat label="Planos Pro" value={overview.data?.proPlans ?? 0} helper="assinaturas ativas" icon={<CircleDollarSign />} color="emerald" /></div><div className="mb-6 mt-6 flex gap-1 rounded-2xl bg-slate-100 p-1"><TabBtn active={tab === "overview"} onClick={() => setTab("overview")} label="Visão geral" /><TabBtn active={tab === "profissionais"} onClick={() => setTab("profissionais")} label={`Profissionais (${professionals.data?.length ?? 0})`} /></div>{tab === "overview" ? <Overview data={overview.data} loading={overview.isLoading} /> : <Professionals data={professionals.data ?? []} loading={professionals.isLoading} activate={(id) => activatePro.mutate({ professionalId: id })} deactivate={(id) => deactivatePro.mutate({ professionalId: id })} pending={activatePro.isPending || deactivatePro.isPending} />}</>}</div></DashboardLayout>;
}

type OverviewData = { recentRequests: Array<{ id: number; category: string; city: string; description: string; status: string }>; recentProfessionals: Array<{ id: number; displayName: string; category: string; city: string; state: string }> } | undefined;
function Overview({ data, loading }: { data: OverviewData; loading: boolean }) { return <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-card"><div className="mb-5 flex items-center justify-between"><div><h2 className="display-font text-xl font-bold text-slate-950">Pedidos recentes</h2><p className="mt-1 text-sm text-slate-500">Atividade de demanda na plataforma</p></div><ClipboardList className="h-5 w-5 text-slate-300" /></div>{loading ? <SkeletonList /> : data?.recentRequests.length ? <div className="divide-y divide-slate-100">{data.recentRequests.map(item => <div key={item.id} className="flex items-center justify-between gap-4 py-4"><div className="min-w-0"><p className="truncate font-bold text-slate-800">{item.category} <span className="font-normal text-slate-400">em</span> {item.city}</p><p className="mt-1 truncate text-xs text-slate-500">{item.description}</p></div><span className="shrink-0 rounded-full bg-blue-50 px-2.5 py-1 text-[11px] font-bold text-blue-700">{item.status}</span></div>)}</div> : <Empty label="Ainda não há pedidos." />}</section><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-card"><div className="mb-5 flex items-center justify-between"><div><h2 className="display-font text-xl font-bold text-slate-950">Profissionais novos</h2><p className="mt-1 text-sm text-slate-500">Oferta entrando por região</p></div><BriefcaseBusiness className="h-5 w-5 text-slate-300" /></div>{loading ? <SkeletonList /> : data?.recentProfessionals.length ? <div className="space-y-3">{data.recentProfessionals.map(item => <div key={item.id} className="flex items-center gap-3 rounded-2xl bg-slate-50 p-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white font-bold text-blue-600 shadow-sm">{item.displayName.slice(0, 1)}</div><div className="min-w-0 flex-1"><p className="truncate font-bold text-slate-800">{item.displayName}</p><p className="truncate text-xs text-slate-500">{item.category} · {item.city}/{item.state}</p></div><ChevronRight className="h-4 w-4 text-slate-300" /></div>)}</div> : <Empty label="Ainda não há profissionais." />}</section></div>; }

type Professional = { id: number; displayName: string; category: string; city: string; state: string; whatsapp: string; plan: "free" | "pro" };
function Professionals({ data, loading, activate, deactivate, pending }: { data: Professional[]; loading: boolean; activate: (id: number) => void; deactivate: (id: number) => void; pending: boolean }) { return <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-card"><div className="mb-5"><h2 className="display-font text-xl font-bold text-slate-950">Gerenciar profissionais</h2><p className="mt-1 text-sm text-slate-500">Ative o plano Pro após confirmar o pagamento via Pix.</p></div>{loading ? <SkeletonList /> : data.length ? <div className="divide-y divide-slate-100">{data.map(pro => <div key={pro.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-blue-600 text-lg font-bold text-white">{pro.displayName.slice(0, 1)}</div><div><div className="flex items-center gap-2"><p className="font-bold text-slate-900">{pro.displayName}</p>{pro.plan === "pro" && <span className="inline-flex items-center gap-1 rounded-full bg-amber-100 px-2 py-0.5 text-[11px] font-bold text-amber-700"><Star className="h-3 w-3" /> Pro</span>}</div><p className="text-xs text-slate-500">{pro.category} · {pro.city}/{pro.state}</p><p className="text-xs text-slate-400">{pro.whatsapp}</p></div></div><div className="flex items-center gap-2 sm:ml-0">{pro.plan === "pro" ? <Button size="sm" variant="outline" onClick={() => deactivate(pro.id)} disabled={pending} className="rounded-xl border-red-200 text-xs text-red-600 hover:bg-red-50"><XCircle className="mr-1 h-3.5 w-3.5" /> Revogar Pro</Button> : <Button size="sm" onClick={() => activate(pro.id)} disabled={pending} className="rounded-xl bg-emerald-600 text-xs font-bold hover:bg-emerald-700"><CheckCircle2 className="mr-1 h-3.5 w-3.5" /> Ativar Pro</Button>}</div></div>)}</div> : <Empty label="Ainda não há profissionais." />}</section>; }
function TabBtn({ active, onClick, label }: { active: boolean; onClick: () => void; label: string }) { return <button onClick={onClick} className={`rounded-xl px-4 py-2 text-sm font-bold transition ${active ? "bg-white text-slate-900 shadow-sm" : "text-slate-500 hover:text-slate-900"}`}>{label}</button>; }
function Stat({ label, value, helper, icon, color }: { label: string; value: number; helper: string; icon: React.ReactNode; color: string }) { const map: Record<string, string> = { blue: "bg-blue-50 text-blue-600", violet: "bg-violet-50 text-violet-600", amber: "bg-amber-50 text-amber-600", emerald: "bg-emerald-50 text-emerald-600" }; return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-card"><div className="flex items-center justify-between"><span className="text-sm font-semibold text-slate-500">{label}</span><span className={`grid h-10 w-10 place-items-center rounded-xl ${map[color]}`}>{icon}</span></div><p className="mt-5 display-font text-3xl font-bold text-slate-950">{value}</p><p className="mt-1 text-xs text-slate-400">{helper}</p></div>; }
function SkeletonList() { return <div className="space-y-3">{[1, 2, 3].map(i => <div className="h-14 animate-pulse rounded-xl bg-slate-100" key={i} />)}</div>; }
function Empty({ label }: { label: string }) { return <div className="rounded-2xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">{label}</div>; }
function Loading() { return <div className="grid min-h-screen place-items-center bg-[#f6f7fb]"><div className="h-8 w-8 animate-spin rounded-full border-2 border-blue-600 border-t-transparent" /></div>; }
