import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Bell, CheckCircle2, Check, ClipboardList, MapPin, MessageCircle, Phone, UserRound, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import ChamaHeader from "@/components/ChamaHeader";
import { toast } from "sonner";

type Tab = "requests" | "proposals";
type CustomerProposal = {
  id: number;
  amountCents: number | null;
  message: string;
  status: string;
  createdAt: Date;
  request: { id: number; category: string; city: string; state: string; description: string };
  professional: { displayName: string; whatsapp: string; phone: string; category: string };
};

export default function CustomerDashboard() {
  const [, setLocation] = useLocation();
  const { user, loading } = useAuth();
  const profile = trpc.customer.me.useQuery(undefined, { enabled: !!user });
  const requests = trpc.customer.requests.useQuery(undefined, { enabled: !!user });
  const proposals = trpc.customer.proposals.useQuery(undefined, { enabled: !!user, refetchInterval: 30000 });
  const notifications = trpc.customer.notifications.useQuery(undefined, { enabled: !!user, refetchInterval: 30000 });
  const utils = trpc.useUtils();
  const decideProposal = trpc.customer.decideProposal.useMutation({ onSuccess: (_, input) => { void utils.customer.proposals.invalidate(); void utils.customer.requests.invalidate(); toast.success(input.decision === "accepted" ? "Proposta aceita. Você já pode falar com o profissional." : "Proposta recusada."); }, onError: error => toast.error(error.message) });
  const markNotificationRead = trpc.customer.markNotificationRead.useMutation({ onSuccess: () => void utils.customer.notifications.invalidate() });
  const save = trpc.customer.saveProfile.useMutation({ onSuccess: () => { profile.refetch(); toast.success("Dados salvos com sucesso."); }, onError: error => toast.error(error.message) });
  const [form, setForm] = useState({ phone: "", city: "", state: "SP" });
  const [activeTab, setActiveTab] = useState<Tab>("requests");

  useEffect(() => { if (profile.data) setForm({ phone: profile.data.phone ?? "", city: profile.data.city, state: profile.data.state }); }, [profile.data]);

  if (loading) return <div className="grid min-h-screen place-items-center bg-[#f6f7fb]"><div className="h-8 w-8 animate-spin rounded-full border-2 border-blue-600 border-t-transparent" /></div>;
  if (!user) return <AuthWall title="Acompanhe seus pedidos" description="Entre para salvar seus dados e acompanhar os profissionais que responderam."><Button onClick={() => setLocation("/login?returnTo=/cliente")} className="bg-blue-600 hover:bg-blue-700">Entrar no ChamaPro</Button></AuthWall>;

  return <div className="min-h-screen bg-[#f6f7fb]"><ChamaHeader /><main className="mx-auto max-w-5xl px-5 py-10 lg:px-8">
    <button onClick={() => setLocation("/")} className="mb-7 flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-blue-600"><ArrowLeft className="h-4 w-4" /> Voltar para a página inicial</button>
    <div className="mb-9 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><span className="mb-3 inline-flex rounded-full bg-blue-100 px-3 py-1 text-xs font-bold uppercase tracking-[.16em] text-blue-700">Área do cliente</span><h1 className="display-font text-4xl font-bold tracking-[-.05em] text-slate-950">Olá, {user.name?.split(" ")[0] ?? "cliente"}.</h1><p className="mt-2 text-slate-500">Acompanhe seus pedidos e as propostas recebidas.</p></div><Button onClick={() => setLocation("/#pedido")} className="w-fit rounded-xl bg-blue-600 font-bold hover:bg-blue-700">Novo pedido</Button></div>
    <NotificationsPanel notifications={notifications.data ?? []} onRead={notificationId => { markNotificationRead.mutate({ notificationId }); setActiveTab("proposals"); }} />
    <div className="mb-5 flex gap-2 rounded-2xl border border-slate-200 bg-white p-1.5 shadow-card"><button onClick={() => setActiveTab("requests")} className={`flex-1 rounded-xl px-4 py-3 text-sm font-bold transition ${activeTab === "requests" ? "bg-blue-600 text-white shadow-sm" : "text-slate-500 hover:bg-slate-50"}`}><span className="inline-flex items-center gap-2"><ClipboardList className="h-4 w-4" /> Meus pedidos <span className="rounded-full bg-white/20 px-2 py-0.5 text-xs">{requests.data?.length ?? 0}</span></span></button><button onClick={() => setActiveTab("proposals")} className={`flex-1 rounded-xl px-4 py-3 text-sm font-bold transition ${activeTab === "proposals" ? "bg-blue-600 text-white shadow-sm" : "text-slate-500 hover:bg-slate-50"}`}><span className="inline-flex items-center gap-2"><MessageCircle className="h-4 w-4" /> Propostas recebidas <span className="rounded-full bg-white/20 px-2 py-0.5 text-xs">{proposals.data?.length ?? 0}</span></span></button></div>
    <div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]">
      <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-card"><div className="mb-6 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-blue-50 text-blue-600"><UserRound className="h-5 w-5" /></div><div><h2 className="font-bold text-slate-900">Seus dados</h2><p className="text-xs text-slate-500">Usados para agilizar o contato</p></div></div><div className="space-y-4"><Field label="Telefone / WhatsApp" icon={<Phone className="h-4 w-4" />}><Input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} placeholder="(19) 99999-9999" /></Field><Field label="Cidade" icon={<MapPin className="h-4 w-4" />}><Input value={form.city} onChange={e => setForm({ ...form, city: e.target.value })} placeholder="Ex.: Araras" /></Field><Field label="Estado" icon={<MapPin className="h-4 w-4" />}><Input maxLength={2} value={form.state} onChange={e => setForm({ ...form, state: e.target.value.toUpperCase() })} /></Field><Button onClick={() => save.mutate(form)} disabled={save.isPending} className="w-full rounded-xl bg-slate-900 font-bold hover:bg-blue-700">{save.isPending ? "Salvando..." : "Salvar dados"}</Button></div></section>
      {activeTab === "requests" ? <RequestsPanel requests={requests.data ?? []} loading={requests.isLoading} onNewRequest={() => setLocation("/#pedido")} /> : <ProposalsPanel proposals={(proposals.data ?? []) as CustomerProposal[]} loading={proposals.isLoading} onDecision={(proposalId, decision) => decideProposal.mutate({ proposalId, decision })} deciding={decideProposal.isPending} />}
    </div>
  </main></div>;
}

function RequestsPanel({ requests, loading, onNewRequest }: { requests: Array<{ id: number; category: string; city: string; description: string; status: string }>; loading: boolean; onNewRequest: () => void }) { return <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-card"><div className="mb-5 flex items-center justify-between"><div><h2 className="display-font text-xl font-bold text-slate-950">Meus pedidos</h2><p className="mt-1 text-sm text-slate-500">Histórico de solicitações</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{requests.length} pedidos</span></div>{loading ? <LoadingCards /> : requests.length ? <div className="space-y-3">{requests.map(item => <div key={item.id} className="rounded-2xl border border-slate-100 bg-slate-50/70 p-4"><div className="flex items-start justify-between gap-4"><div><p className="font-bold text-slate-900">{item.category}</p><p className="mt-1 text-sm text-slate-500">{item.city} · {item.description}</p></div><span className="inline-flex items-center gap-1 rounded-full bg-amber-50 px-2 py-1 text-[11px] font-bold text-amber-700"><span className="h-1.5 w-1.5 rounded-full bg-amber-500" /> {item.status === "open" ? "Aberto" : item.status}</span></div></div>)}</div> : <EmptyState title="Você ainda não tem pedidos" description="Quando precisar, o próximo passo está a um clique." action="Pedir orçamento" onClick={onNewRequest} />}</section>; }

function ProposalsPanel({ proposals, loading, onDecision, deciding }: { proposals: CustomerProposal[]; loading: boolean; onDecision: (proposalId: number, decision: "accepted" | "rejected") => void; deciding: boolean }) { return <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-card"><div className="mb-5 flex items-center justify-between"><div><h2 className="display-font text-xl font-bold text-slate-950">Propostas recebidas</h2><p className="mt-1 text-sm text-slate-500">Profissionais interessados nos seus pedidos.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{proposals.length} propostas</span></div>{loading ? <LoadingCards /> : proposals.length ? <div className="space-y-4">{proposals.map(proposal => <ProposalCard key={proposal.id} proposal={proposal} onDecision={onDecision} deciding={deciding} />)}</div> : <EmptyState title="Nenhuma proposta ainda" description="Assim que um profissional responder ao seu pedido, ela aparecerá aqui." />}</section>; }

function ProposalCard({ proposal, onDecision, deciding }: { proposal: CustomerProposal; onDecision: (proposalId: number, decision: "accepted" | "rejected") => void; deciding: boolean }) { const number = (proposal.professional.whatsapp || proposal.professional.phone).replace(/\D/g, ""); const message = `Olá ${proposal.professional.displayName}, vi sua proposta para meu pedido de ${proposal.request.category} no ChamaPro.`; return <article className="rounded-2xl border border-slate-100 bg-slate-50/70 p-4"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-md bg-blue-100 px-2 py-1 text-[11px] font-bold uppercase tracking-wide text-blue-700">{proposal.request.category}</span><span className="text-xs text-slate-400">{new Date(proposal.createdAt).toLocaleDateString("pt-BR")}</span></div><h3 className="mt-3 font-bold text-slate-900">{proposal.professional.displayName}</h3><p className="mt-1 text-sm text-slate-500">Para: {proposal.request.city} · {proposal.request.description}</p></div>{proposal.amountCents ? <span className="whitespace-nowrap rounded-full bg-emerald-50 px-3 py-1.5 text-sm font-bold text-emerald-700">R$ {(proposal.amountCents / 100).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}</span> : <span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-500">A combinar</span>}</div><p className="mt-4 rounded-xl bg-white p-3 text-sm leading-6 text-slate-600">{proposal.message}</p><div className="mt-4 flex flex-wrap gap-2">{proposal.status === "sent" && <><Button onClick={() => onDecision(proposal.id, "accepted")} disabled={deciding} size="sm" className="rounded-xl bg-blue-600 font-bold hover:bg-blue-700"><Check className="mr-1 h-4 w-4" /> Aceitar proposta</Button><Button onClick={() => onDecision(proposal.id, "rejected")} disabled={deciding} size="sm" variant="outline" className="rounded-xl text-red-600 hover:bg-red-50"><X className="mr-1 h-4 w-4" /> Recusar</Button></>}{proposal.status === "accepted" && <a href={`https://wa.me/${number}?text=${encodeURIComponent(message)}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white transition hover:bg-emerald-700"><MessageCircle className="h-4 w-4" /> Falar pelo WhatsApp</a>}<span className={`inline-flex items-center rounded-xl px-3 py-2 text-xs font-bold ${proposal.status === "accepted" ? "bg-emerald-50 text-emerald-700" : proposal.status === "rejected" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}`}>{proposal.status === "accepted" ? "Aceita" : proposal.status === "rejected" ? "Recusada" : "Aguardando decisão"}</span></div></article>; }

function NotificationsPanel({ notifications, onRead }: { notifications: Array<{ id: number; title: string; body: string; readAt: Date | null; createdAt: Date }>; onRead: (notificationId: number) => void }) { const unread = notifications.filter(item => !item.readAt); if (!notifications.length) return null; return <section className="mb-5 rounded-3xl border border-blue-100 bg-blue-50/70 p-4 shadow-card"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-blue-600 text-white"><Bell className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-bold text-slate-900">Notificações {unread.length > 0 && <span className="ml-1 rounded-full bg-blue-600 px-2 py-0.5 text-xs text-white">{unread.length} nova{unread.length > 1 ? "s" : ""}</span>}</h2><p className="text-xs text-slate-500">Atualizações sobre suas propostas.</p></div></div><div className="mt-3 space-y-2">{notifications.slice(0, 3).map(item => <button key={item.id} onClick={() => !item.readAt && onRead(item.id)} className={`flex w-full items-start gap-3 rounded-xl p-3 text-left transition ${item.readAt ? "bg-white/60" : "bg-white shadow-sm hover:bg-white"}`}><div className={`mt-1 h-2 w-2 shrink-0 rounded-full ${item.readAt ? "bg-slate-300" : "bg-blue-600"}`} /><span className="min-w-0"><span className="block text-sm font-bold text-slate-800">{item.title}</span><span className="mt-0.5 block text-xs text-slate-500">{item.body}</span></span></button>)}</div></div></div></section>; }

function LoadingCards() { return <div className="space-y-3">{[1, 2, 3].map(item => <div key={item} className="h-24 animate-pulse rounded-2xl bg-slate-100" />)}</div>; }
function EmptyState({ title, description, action, onClick }: { title: string; description: string; action?: string; onClick?: () => void }) { return <div className="rounded-2xl border border-dashed border-slate-200 p-8 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-slate-300" /><p className="mt-3 font-bold text-slate-700">{title}</p><p className="mt-1 text-sm text-slate-500">{description}</p>{action && <Button onClick={onClick} variant="outline" className="mt-4 rounded-xl">{action}</Button>}</div>; }
function Field({ label, icon, children }: { label: string; icon: React.ReactNode; children: React.ReactNode }) { return <label className="block"><span className="mb-2 flex items-center gap-2 text-sm font-bold text-slate-700">{icon}{label}</span>{children}</label>; }
function AuthWall({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="grid min-h-screen place-items-center bg-[#f6f7fb] p-5"><div className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-8 text-center shadow-card"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-blue-600 text-2xl font-black text-white">C</div><h1 className="display-font mt-6 text-2xl font-bold text-slate-950">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p><div className="mt-6">{children}</div></div></div>; }
