import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import PixModal from "@/components/PixModal";
import { ArrowLeft, ArrowRight, BriefcaseBusiness, MapPin, MessageCircle, Plus, Sparkles, Star, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import ChamaHeader from "@/components/ChamaHeader";
import { toast } from "sonner";

const categories = ["Elétrica", "Encanamento", "Ar-condicionado", "Câmeras e segurança", "Automação residencial", "Marcenaria / montagem", "Limpeza", "Manutenção geral", "Outro"];
const emptyForm = { displayName: "", phone: "", whatsapp: "", category: "Elétrica", city: "", state: "SP", serviceArea: "", bio: "" };

type Lead = { id: number; matchId: number; category: string; city: string; state: string; description: string; nameSnapshot: string; contactPhone?: string | null; matchStatus: string };

export default function ProfessionalDashboard() {
  const [, setLocation] = useLocation();
  const { user, loading } = useAuth();
  const profile = trpc.professional.me.useQuery(undefined, { enabled: !!user });
  const leads = trpc.professional.leads.useQuery(undefined, { enabled: !!user && !!profile.data });
  const billing = trpc.billing.history.useQuery(undefined, { enabled: !!user && !!profile.data });
  const save = trpc.professional.saveProfile.useMutation({ onSuccess: () => { profile.refetch(); toast.success("Perfil profissional salvo."); }, onError: error => toast.error(error.message) });
  const viewed = trpc.professional.markViewed.useMutation({ onSuccess: () => leads.refetch() });
  const checkout = trpc.professional.checkout.useMutation({ onSuccess: data => { if (data.url) { toast.success("Abrindo checkout seguro do Stripe."); window.open(data.url, "_blank"); } }, onError: error => toast.error(error.message) });
  const proposal = trpc.professional.sendProposal.useMutation({ onSuccess: () => { setSelected(null); toast.success("Proposta enviada para o cliente."); }, onError: error => toast.error(error.message) });
  const [form, setForm] = useState(emptyForm);
  const [selected, setSelected] = useState<Lead | null>(null);
  const [showPix, setShowPix] = useState(false);

  useEffect(() => { if (profile.data) setForm({ displayName: profile.data.displayName, phone: profile.data.phone, whatsapp: profile.data.whatsapp, category: profile.data.category, city: profile.data.city, state: profile.data.state, serviceArea: profile.data.serviceArea ?? "", bio: profile.data.bio ?? "" }); }, [profile.data]);

  if (loading) return <Loading />;
  if (!user) return <AuthWall title="Conquiste clientes perto de você" description="Crie seu perfil, receba pedidos da sua região e fale pelo WhatsApp."><Button onClick={() => setLocation("/login?returnTo=/profissional")} className="bg-blue-600 hover:bg-blue-700">Entrar para começar</Button></AuthWall>;

  const isSetup = !!profile.data;
  return <div className="min-h-screen bg-[#f6f7fb]"><ChamaHeader /><main className="mx-auto max-w-6xl px-5 py-10 lg:px-8">
    <button onClick={() => setLocation("/")} className="mb-7 flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-blue-600"><ArrowLeft className="h-4 w-4" /> Voltar para a página inicial</button>
    {!isSetup ? <ProfileSetup form={form} setForm={setForm} onSave={() => save.mutate(form)} saving={save.isPending} /> : <>
      <div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><span className="mb-3 inline-flex rounded-full bg-blue-100 px-3 py-1 text-xs font-bold uppercase tracking-[.16em] text-blue-700">Painel profissional</span><h1 className="display-font text-4xl font-bold tracking-[-.05em] text-slate-950">Sua próxima oportunidade está perto.</h1><p className="mt-2 text-slate-500">Olá, {profile.data!.displayName}. Aqui você acompanha os pedidos compatíveis com sua região.</p></div><div className="flex flex-wrap gap-3"><span className={`inline-flex items-center gap-2 rounded-full px-3 py-2 text-sm font-bold ${profile.data!.plan === "pro" ? "bg-amber-100 text-amber-800" : "bg-white text-slate-600"}`}><Star className="h-4 w-4" /> Plano {profile.data!.plan === "pro" ? "Pro" : "Essencial"}</span>{profile.data!.plan !== "pro" && <><Button onClick={() => checkout.mutate()} disabled={checkout.isPending} className="rounded-xl bg-blue-600 font-bold hover:bg-blue-700">{checkout.isPending ? "Abrindo..." : "Assinar com cartão"}<Sparkles className="ml-2 h-4 w-4" /></Button><Button onClick={() => setShowPix(true)} variant="outline" className="rounded-xl border-blue-200 font-bold text-blue-700 hover:bg-blue-50">Pagar via Pix</Button></>}</div></div>
      <div className="mb-6 grid gap-4 sm:grid-cols-3"><Metric label="Leads compatíveis" value={String(leads.data?.length ?? 0)} icon={<BriefcaseBusiness />} tone="blue" /><Metric label="Novos hoje" value={String(leads.data?.filter(item => item.matchStatus === "new").length ?? 0)} icon={<Sparkles />} tone="amber" /><Metric label="Sua região" value={profile.data!.city} icon={<MapPin />} tone="emerald" /></div>
      <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-card"><div className="mb-5 flex items-center justify-between"><div><h2 className="display-font text-xl font-bold text-slate-950">Pedidos para você</h2><p className="mt-1 text-sm text-slate-500">Leads organizados por categoria e cidade.</p></div><span className="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-700">{leads.data?.length ?? 0} oportunidades</span></div>{leads.isLoading ? <div className="grid gap-3 md:grid-cols-2">{[1, 2, 3, 4].map(item => <div key={item} className="h-36 animate-pulse rounded-2xl bg-slate-100" />)}</div> : leads.data?.length ? <div className="grid gap-4 md:grid-cols-2">{leads.data.map(lead => <LeadCard key={lead.matchId} lead={lead as Lead} onView={() => viewed.mutate({ matchId: lead.matchId })} onProposal={() => setSelected(lead as Lead)} />)}</div> : <div className="rounded-2xl border border-dashed border-slate-200 p-10 text-center"><Plus className="mx-auto h-8 w-8 text-slate-300" /><p className="mt-3 font-bold text-slate-700">O próximo lead começa com um perfil completo</p><p className="mt-1 text-sm text-slate-500">Assim que houver um pedido de {profile.data!.category} em {profile.data!.city}, ele aparece aqui.</p></div>}</section>
      <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-card"><div className="flex items-center justify-between"><div><h2 className="display-font text-lg font-bold text-slate-950">Assinatura e cobranças</h2><p className="mt-1 text-sm text-slate-500">Identificadores de cobrança ficam sincronizados com o Stripe.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700">{profile.data!.plan === "pro" ? "Ativa" : "Plano gratuito"}</span></div>{billing.data?.length ? <div className="mt-4 divide-y divide-slate-100">{billing.data.slice(0, 4).map(record => <div key={record.id} className="flex items-center justify-between gap-4 py-3 text-sm"><span className="font-semibold text-slate-700">{record.eventType}</span><span className="text-slate-400">{new Date(record.createdAt).toLocaleDateString("pt-BR")}</span></div>)}</div> : <div className="mt-4 rounded-2xl bg-slate-50 p-4 text-sm text-slate-500">Ainda não há eventos de cobrança registrados. Ao assinar, o Stripe atualiza este histórico automaticamente.</div>}</section>
      {showPix && <PixModal onClose={() => setShowPix(false)} />}
      {selected && <ProposalComposer lead={selected} onClose={() => setSelected(null)} onSend={(message, amount) => proposal.mutate({ requestId: selected.id, message, amountCents: amount ? Math.round(Number(amount) * 100) : undefined })} sending={proposal.isPending} />}
    </>}
  </main></div>;
}

function ProfileSetup({ form, setForm, onSave, saving }: { form: typeof emptyForm; setForm: (form: typeof emptyForm) => void; onSave: () => void; saving: boolean }) { return <div className="mx-auto max-w-3xl rounded-3xl border border-slate-200 bg-white p-6 shadow-card md:p-9"><div className="mb-8 flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-blue-600 text-white"><BriefcaseBusiness /></div><div><span className="text-xs font-bold uppercase tracking-[.16em] text-blue-600">Primeiro passo</span><h1 className="display-font mt-1 text-3xl font-bold tracking-[-.05em] text-slate-950">Crie seu perfil profissional.</h1><p className="mt-2 text-sm leading-6 text-slate-500">Esses dados são usados para encontrar pedidos compatíveis perto de você.</p></div></div><div className="grid gap-4 md:grid-cols-2"><Field label="Nome que aparece para clientes"><Input value={form.displayName} onChange={e => setForm({ ...form, displayName: e.target.value })} placeholder="Ex.: João Elétrica" /></Field><Field label="Categoria principal"><select className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>{categories.map(item => <option key={item}>{item}</option>)}</select></Field><Field label="Telefone"><Input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} placeholder="(19) 99999-9999" /></Field><Field label="WhatsApp para receber leads"><Input value={form.whatsapp} onChange={e => setForm({ ...form, whatsapp: e.target.value })} placeholder="5519999999999" /></Field><Field label="Cidade"><Input value={form.city} onChange={e => setForm({ ...form, city: e.target.value })} placeholder="Ex.: Araras" /></Field><Field label="Estado"><Input maxLength={2} value={form.state} onChange={e => setForm({ ...form, state: e.target.value.toUpperCase() })} /></Field><Field label="Área de atendimento"><Input value={form.serviceArea} onChange={e => setForm({ ...form, serviceArea: e.target.value })} placeholder="Ex.: Centro e bairros próximos" /></Field><Field label="Mini bio"><Input value={form.bio} onChange={e => setForm({ ...form, bio: e.target.value })} placeholder="Conte brevemente sua experiência" /></Field></div><Button onClick={onSave} disabled={saving} className="mt-6 w-full rounded-xl bg-blue-600 font-bold hover:bg-blue-700">{saving ? "Salvando perfil..." : "Ativar meu perfil"}<ArrowRight className="ml-2 h-4 w-4" /></Button></div>; }
function LeadCard({ lead, onView, onProposal }: { lead: Lead; onView: () => void; onProposal: () => void }) { return <article onClick={onView} className={`rounded-2xl border p-5 transition hover:-translate-y-0.5 hover:shadow-card ${lead.matchStatus === "new" ? "border-blue-200 bg-blue-50/40" : "border-slate-100 bg-white"}`}><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="rounded-md bg-white px-2 py-1 text-[11px] font-bold uppercase tracking-wide text-blue-700 shadow-sm">{lead.category}</span>{lead.matchStatus === "new" && <span className="h-2 w-2 rounded-full bg-blue-600" />}</div><h3 className="mt-3 font-bold text-slate-900">{lead.nameSnapshot} precisa de ajuda</h3><p className="mt-1 flex items-center gap-1 text-sm text-slate-500"><MapPin className="h-3.5 w-3.5" /> {lead.city} — {lead.state}</p></div><span className="text-xs font-semibold text-slate-400">#{lead.id}</span></div><p className="mt-4 line-clamp-2 text-sm leading-6 text-slate-600">{lead.description}</p><div className="mt-5 flex flex-wrap gap-2"><Button onClick={e => { e.stopPropagation(); onProposal(); }} size="sm" className="rounded-lg bg-slate-900 font-bold hover:bg-blue-700">Enviar proposta</Button>{lead.contactPhone ? <a onClick={e => e.stopPropagation()} href={`https://wa.me/${lead.contactPhone.replace(/\D/g, "")}?text=${encodeURIComponent(`Olá ${lead.nameSnapshot}, vi seu pedido de ${lead.category} no ChamaPro.`)}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 rounded-lg border border-emerald-200 bg-emerald-50 px-3 text-sm font-bold text-emerald-700 hover:bg-emerald-100"><MessageCircle className="h-4 w-4" /> WhatsApp</a> : <span className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 bg-slate-50 px-3 text-sm font-bold text-slate-400"><MessageCircle className="h-4 w-4" /> WhatsApp não informado</span>}</div></article>; }
function ProposalComposer({ lead, onClose, onSend, sending }: { lead: Lead; onClose: () => void; onSend: (message: string, amount: string) => void; sending: boolean }) { const [message, setMessage] = useState(`Olá ${lead.nameSnapshot}, sou especialista em ${lead.category} e posso te ajudar. Posso entender melhor o serviço?`); const [amount, setAmount] = useState(""); return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-5 backdrop-blur-sm"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><span className="text-xs font-bold uppercase tracking-[.16em] text-blue-600">Nova proposta</span><h2 className="display-font mt-1 text-2xl font-bold text-slate-950">Para {lead.nameSnapshot}</h2></div><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X /></button></div><label className="mt-6 block text-sm font-bold text-slate-700">Mensagem<textarea className="mt-2 min-h-28 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500" value={message} onChange={e => setMessage(e.target.value)} /></label><label className="mt-4 block text-sm font-bold text-slate-700">Valor estimado (opcional)<Input className="mt-2" value={amount} onChange={e => setAmount(e.target.value)} placeholder="Ex.: 350" /></label><div className="mt-6 flex gap-3"><Button variant="outline" onClick={onClose} className="flex-1 rounded-xl">Cancelar</Button><Button onClick={() => onSend(message, amount)} disabled={sending} className="flex-1 rounded-xl bg-blue-600 font-bold hover:bg-blue-700">{sending ? "Enviando..." : "Enviar proposta"}</Button></div></div></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-sm font-bold text-slate-700">{label}</span>{children}</label>; }
function Metric({ label, value, icon, tone }: { label: string; value: string; icon: React.ReactNode; tone: "blue" | "amber" | "emerald" }) { const colors = { blue: "bg-blue-50 text-blue-600", amber: "bg-amber-50 text-amber-600", emerald: "bg-emerald-50 text-emerald-600" }; return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-card"><div className="flex items-center justify-between"><span className="text-sm font-semibold text-slate-500">{label}</span><div className={`grid h-9 w-9 place-items-center rounded-xl ${colors[tone]}`}>{icon}</div></div><p className="mt-4 display-font text-2xl font-bold text-slate-950">{value}</p></div>; }
function Loading() { return <div className="grid min-h-screen place-items-center bg-[#f6f7fb]"><div className="h-8 w-8 animate-spin rounded-full border-2 border-blue-600 border-t-transparent" /></div>; }
function AuthWall({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="grid min-h-screen place-items-center bg-[#f6f7fb] p-5"><div className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-8 text-center shadow-card"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-blue-600 text-2xl font-black text-white">C</div><h1 className="display-font mt-6 text-2xl font-bold text-slate-950">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p><div className="mt-6">{children}</div></div></div>; }
